DATA:
  DATASET: kadid
  BATCH_SIZE: 128
  PATCH_NUM: 10
  CROP_SIZE: (224,224)
SET:
  COUNT: 81
MODEL:
  TYPE: purevit
  NAME: vit_small_pre
  DROP_PATH_RATE: 0.0
  VIT:
    PATCH_SIZE: 16
    EMBED_DIM: 384
    DEPTH: 12
    NUM_HEADS: 6
    MLP_RATIO: 4
    QKV_BIAS: True
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/pws/IQA/deit_3_small_224_1k.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4 # 4096 batch-size
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
   NAME: step
   DECAY_EPOCHS: 3
